# Generated by Django 5.2.7 on 2025-10-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='RepairAndMaintenanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('front_load', models.CharField(max_length=255)),
                ('back_load', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='FuelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=255)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('front_load', models.CharField(max_length=255)),
                ('back_load', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
    ]
