# Generated by Django 5.2.7 on 2025-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('truck_type', models.CharField(max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('front_load', models.CharField(blank=True, max_length=255, null=True)),
                ('back_load', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
